<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IHM\**" />
    <EmbeddedResource Remove="IHM\**" />
    <None Remove="IHM\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />
  </ItemGroup>

</Project>